version: '2'
services:
  mysql:
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=password
  mediawiki:
    build:
      context: .
      dockerfile: docker/mediawiki/Dockerfile
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - ./data/images:/var/www/html/w/images
      - ./data/settings.d:/var/www/html/w/settings.d
