version: '2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    image: cllu/mediawiki-elasticsearch:1.7.5-1
    networks:
      mediawiki-internal:
        ipv4_address: 172.27.1.10
  mysql:
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mediawiki
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
    networks:
      mediawiki-internal:
        ipv4_address: 172.27.1.11
  parsoid:
    build:
      context: .
      dockerfile: docker/parsoid/Dockerfile
    image: cllu/mediawiki-parsoid:1.27-1
    networks:
      mediawiki-internal:
        ipv4_address: 172.27.1.3
  redis:
    image: redis:2.8.23
    networks:
      - ocg-internal
  ocg:
    build:
      context: .
      dockerfile: docker/ocg/Dockerfile
    image: cllu/mediawiki-ocg:1.27-2
    networks:
      ocg-internal:
      mediawiki-internal:
        ipv4_address: 172.27.1.4
  mediawiki:
    build:
      context: .
      dockerfile: docker/mediawiki/Dockerfile
    image: cllu/mediawiki:1.27-5
    ports:
      - 80:80
    environment:
      WG_SITENAME: MediaWiki
      WG_DBNAME: mediawiki
      WG_SERVER: http://192.168.99.100
      WG_SECRET_KEY: ee0efe6c8b4bc1ee5ccd906ad783aeb20115f061a3f9d85e6850612104920701
      WG_UPGRADE_KEY: 08882e35d74f30cf
      WG_LOGO:
      WG_SMTP_HOST:
      WG_SMTP_IDHOST:
      WG_SMTP_PORT:
      WG_SMTP_USERNAME:
      WG_SMTP_PASSWORD:
      WG_SECRET_READ_TOKEN: ee5ccd906ad783aeb2011
      WG_WHITELIST_READ: Secret|Another Secret
    volumes:
      - ./data/images:/var/www/html/w/images
    networks:
      mediawiki-internal:
        ipv4_address: 172.27.1.2

networks:
  mediawiki-internal:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.27.1.0/24
        gateway: 172.27.1.1
  ocg-internal:
    driver: bridge
