version: '2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    image: cllu/mediawiki-elasticsearch:1.7.5-1
  mysql:
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mediawiki
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
  parsoid:
    build:
      context: .
      dockerfile: docker/parsoid/Dockerfile
    image: cllu/mediawiki-parsoid:1.26-1
  mediawiki:
    build:
      context: .
      dockerfile: docker/mediawiki/Dockerfile
    image: cllu/mediawiki:1.26-10
    ports:
      - 80:80
    links:
      - elasticsearch
      - mysql
      - parsoid
    environment:
      WG_SITENAME: MediaWiki
      WG_DBNAME: mediawiki
      WG_SERVER: http://192.168.99.100
      WG_SECRET_KEY: ee0efe6c8b4bc1ee5ccd906ad783aeb20115f061a3f9d85e6850612104920701
      WG_UPGRADE_KEY: 08882e35d74f30cf
      WG_LOGO:
      WG_SMTP_HOST:
      WG_SMTP_IDHOST:
      WG_SMTP_PORT:
      WG_SMTP_USERNAME:
      WG_SMTP_PASSWORD:
    volumes:
      - ./data/images:/var/www/html/w/images
